Selection and high-level pruning
--------------------------------
The first phase concerns only the projects unknown to you and little talked about.
There is no need to go through the first stage for legitimate projects such as Solana, Uniswap or Filecoin. Therefore, we will proceed directly to https://github.com/FundamentalFramework/Framework/blob/main/2.Qualitative_Analysis.adoc[Phase 2^].

An example of projects to put under the lens of the first phase could be https://www.coingecko.com/en/coins/bitkub-coin/[Bitkub Coin (KUB)^], https://www.coingecko.com/en/coins/radio-caca/[Radio Caca (RACA)^] or https://www.coingecko.com/it/monete/xido-finance/[Xido Finance (XIDO)^]

(These are examples only, no opinion on the feasibility of the project)

The first action that will be taken in evaluating a project is a general overview of aggregation platforms such as Coingecko or Coinmarketcap.
Given a first look at the quotes, marketcap, volumes and exchanges that list the token, we review the social twitter page, the official website, the block explorer and github.

Let's see them in more detail:

* 1. *Marketcap:* In the initial phase, a reading of the capitalization is quite fundamental because by going ahead with the analysis you can get an idea of the value of a network compared to the volumes and the Exchanges that quote it.
Taking https://www.coingecko.com/it/monete/xido-finance/[Xido Finance (XIDO)^] as an example again, as of this writing, the market capitalization is *USD 328,234,675* with a volume of *USD 7,676*, technically the volume is *0.0023%* of the market capitalization. For this factor alone, a red flag could be raised by paying close attention to the next steps before decreeing a verdict.

* 2. *Volumes-Exchange:* This step is to evaluate how many Exchanges support the token and the generated volume. It is important to evaluate who is currently listing the token if, top-level exchanges such as Binance, Coinbase, Kraken, Okx etc. it is useful to keep in mind that a project may take longer to be adopted, an organic scaling takes more time. Therefore, if a project is rated positively, Exchange Top level support may be a matter of time.

* 3. *Social-Twitter:* Twitter is the dominant social network in the Crypto sphere, there are other social networks that are strong such as Discord, Reddit or Telegram Groups, but let's focus only on Twitter as it is used as the main channel for official communications by all the major players in the market. We can see how much a profile is followed, what is the level of interaction and involvement with the community. What people think in replies to tweets is also important. Apps like https://santiment.net/[Santiment^] can give you great support thanks to their social metrics and keywords. Twitter is infested with bots and rogue players could alter metrics like Likes, Retweets, comments and followers. There are software that can help you in this, but a careful analysis of the profile is enough to decide a reasonable opinion. Furthermore, verified profiles are certainly more trusted and deemed by Twitter to be authentic, known and active.

* 4. *Official site:* Let's take a look at the official site to understand who they are, what they do, whether a foundation or for-profit company has been established (the https://github.com/FundamentalFramework/Framework/blob/main/2.Qualitative_Analysis.adoc[Phase 2.^] a useful tool will be recommended for an in-depth evaluation of this 'last).
There must be links to social networks, githubs and links to documentation. It happens that in some cases the team is not present on the site, it is therefore advisable to check the Whitepaper. If the objective of the project or the technology used is not clear, a high-level reading of the documentation is appropriate.

* 5. *Block Explorer:* Here we analyze the number of transactions and the total addresses. A first approach to understand how many transactions are taking place on that network and to identify if the number of addresses is growing over time. If a token has been in the market for a year with only 3k Holders and just over 1k-2k transactions, raise the red flag.
Case: https://etherscan.io/token/0xf6650117017ffd48b725b4ec5a00b414097108a7[Xido Finance (XIDO)^] holds just over 500 Holders and approximately 1,800 Transactions. The frequency of updates is also important, if the token exists only on the Ethereum chain and this has few transactions in the last 24h it certainly has little traction. Remember that these are quick assessments that can be superficial, but over time you will develop a tact to quickly recognize if the project you are analyzing will pass the test.
Bad gamers could write bots to alter number of transactions and addresses, so don't stick to just these two metrics when digging deeper in later stages.

* 6. *Github:* Finally we move on to the repository and check how many contributors are involved, how many stars received, forks created, how many are watching it. This is a high-level overview, we will go deeper into the next steps.
Case: https://github.com/xidofinance?tab=repositories/[Xido Finance (XIDO)^] hasn't released updates for almost a year, they are all forks and their repositories have received appreciation that can be counted on the fingers of a carpenter's hand.

*Conclusion:* Xido Finance (XIDO) obviously did not pass the test. This served as an extreme case but in the cryptocurrency market it is chock full of similar projects.
This first phase is useful for eliminating the worst projects at the root and which is believed, we have no hope in the long term. The subsequent phases are more demanding and take longer, therefore a first rapid thinning is essential to optimize the work and the time available.

*Estimated time: ~ 20 minutes*
