Qualitative Analysis
---------------------

Today we will analyze the qualitative part that distinguishes a cryptocurrency project. Before starting, it is good to remember that the sector is still young and there are still no consolidated metrics in the evaluation of a project, therefore, we must adapt with the evolution of the ecosystem by reviewing and adjusting the parameters over time. So this is a Work in Progress construction process that will probably last several years before acquiring a solid and validated foundation over time.

Fundamental analysis in financial markets had its foundation in the mainstream around 1934 when Benjamin Graham and David Dodd finished writing the https://www.amazon.com/Security-Analysis-Foreword-Buffett-Editions/dp/0071592539Security/[Analysis book^] that had begun 4 years earlier.

The birth of Bitcoin was the genesis of a completely new asset class, this only 13 years ago, giving rise to a technological revolution from which various sectors were born. Ethereum was born 7 years ago giving life to the economy of smart contract platforms. The technologies that currently power Blockchain projects are still experimental, with a high risk of failure, therefore we must be wary of excessive optimistic assessments that are easy to come across in Cryptocurrency.

Many of the high-potential projects of 2017 today are networks that are still active, producing blocks and transactions, but the native token has achieved negligible performance and in some cases today you would find yourself at a loss.
Below you will find a list of the top 10 cryptocurrencies photographed by https://coinmarketcap.com/it/historical/20170711/[CMC on 11 July 2017^] (5 years ago at the time of writing these lines) compared to current prices.

[options="header,footer"]
|=======================
|Rank '17 to '22|Crypto|Price 11 Jul ‘17|Price 11 Jul ‘22|Performance
|1-1| Bitcoin| $2,305| $19,970.56|-
|2-2| Ethereum| $197.40| $1,097.24|-
|3-7| XRP| $0.185| $0.3143|-
|4-20| Litecoin| $45.33| $48.77|-
|5-29| Ethereum Classic| $14.72| $14.19|-
|6-75| Dash| $165.73| $41.58|-
|7-87| Nem| $0.1193| $0.03793|-
|8-27| Monero| $37.14| $127.02|-
|9-55| IOTA| $0.1876| $0.2659|-
|10-0| BitConnect| $55.07| $0|-
|-|Total Return 

(Hypothetical investment, 
$10k*coin)|Investment  start $100,000|Current balance $242,058|Average +242,05%
|=======================

The entry at the bottom of the table, Total Return, indicates a hypothetical buy and hold investment of $ 10,000 allocated to each coin, for a total of $ 100,000.
Each crypto weighs 10% in the index.
Today the portfolio would have earned an average return of 242.05% with a final balance of $ 242,058.
BTC and ETH today would weigh 59.50% and XMR 14.20% for a total of 73.80%!
Therefore 30% of the coins (from the initial investment) yielded ~ 74% of the entire portfolio.
Everything else is questionable.

This preamble serves as a general introduction before moving on to the various stages.
Today there are only 2 quality coins and they are BTC and ETH. Stop.
Over time, new unicorns will be born (someone in the magnifying glass is present), but they will have to pass the test of time, that is, overcome prolonged drawdowns knowing how to recover in a healthy way and, consolidating their positioning in the markets by creating real use cases with effects. network and increasing adoption rates.

So it is always good to remember that the future is never linear and well defined, we must adapt to the markets as to life. By analogy, it would be like putting ourselves in the car at night, even if you already know the destination from point A to point B you need the headlights that illuminate the road, the headlights illuminate about 100 meters. 100 meters at a time you arrive at your destination. You could change the road due to work in progress and lengthen it by a few minutes, or run into thunderstorms that would slow down the journey but, the important thing is to do it one step at a time. 100 meters at a time. There are no loopholes, you have to get your hands dirty.

Now let's dive in!

First there are 6 factors that I am looking at when evaluating a project and they are the following:

1.  The team
2.  Corporate structure
3.  Whitepaper and Documentation
4.  Tokenomics
5.  Road map
6.  Community involvement and ecosystem development
7.  Conclusion

The Team
-------

Although past performance is no guarantee of future performance, a good team certainly has more resources than those without an important background, but remember that even the greatest can fail, for a variety of reasons. Having said that, here is a failure that if it had been in the crypto market would have created disbelief and disdain.

https://www.cnbc.com/2020/10/21/quibi-to-shut-down-after-just-6-months.html/[Quibi^] was a video streaming service founded by https://en.wikipedia.org/wiki/Jeffrey_Katzenberg[Jeffrey Katzenberg^] (co-founder with Steven Spielberg and David Geffen of the production company DreamWorks SKG) and https://en.wikipedia.org/wiki/Meg_Whitman[Meg Whitman^] (US business executive, known for having been at the helm for two decades before eBay and then Hewlett Packard) in the role of CEO. The company raised $ 2 billion from Disney and other investors, but ultimately had to throw in the towel, give some of the money back to the investors and liquidate the company. If they had launched an IEO on Binance, the token was certainly the bet of the year, even housewives would have joined the game.

So, since we cannot predict with certainty the success of others, we can however ask ourselves some legitimate questions, here are some of them:

* Are they people with a track record of excellence in prestigious companies?

* Have they created successful companies with multi-million dollar exits in the past?

* Is the team anonymous?
  - If so, why?

* Is anyone on the team a suspect or have they had legal problems in the past relating to fraudulent actions, pyramid schemes or similar situations?

* Is the team public but are they unknown to the public without a demonstrable track record?
  - If so, are they incredibly talented and motivated? (example: Bill gates, Steve jobs, Larry Page - Sergey Brin or Vitalik Buterin were complete strangers at their debut without a track record of excellence, yet, they have changed and are changing the world).
  
These are some questions we can ask ourselves to understand who we are facing, the team must be healthy and free from all problems, fraud and dishonesty.
Better to lose an opportunity than to lose money.

Corporate structure
------------------

It is always useful to understand the legal entity behind a project, in Ethereum there is a foundation that sponsors and encourages the development and sustainability of the network in the long term through grants. One example is developer https://prysmaticlabs.com/[prysmaticlabs^], a team of software engineers that builds the technical infrastructure as well as the ongoing development of the Prysm consensus client. Furthermore, the Ethereum Foundation finances dozens of projects ranging from community development, education, promotes research and constantly invests in technological development: consensus layer, L2 scaling and user experience.




















